<a href="https://colab.research.google.com/github/ahmadzulfiqar001/python-100-days-beginner-to-advance-/blob/main/Day_21_of_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas tutorial

this notebook explains

In [ ]:
#install libraries

#pip install pandas
#pip install numpy

# import libraries

In [1]:
import pandas as pd
import numpy as np

In [3]:
# object creation

s= pd.Series([1,2,3, np.nan,4,5,6])
s

0    1.0
1    2.0
2    3.0
3    NaN
4    4.0
5    5.0
6    6.0
dtype: float64

In [8]:
dates = pd.date_range("20250401", periods=30)
dates

DatetimeIndex(['2025-04-01', '2025-04-02', '2025-04-03', '2025-04-04',
               '2025-04-05', '2025-04-06', '2025-04-07', '2025-04-08',
               '2025-04-09', '2025-04-10', '2025-04-11', '2025-04-12',
               '2025-04-13', '2025-04-14', '2025-04-15', '2025-04-16',
               '2025-04-17', '2025-04-18', '2025-04-19', '2025-04-20',
               '2025-04-21', '2025-04-22', '2025-04-23', '2025-04-24',
               '2025-04-25', '2025-04-26', '2025-04-27', '2025-04-28',
               '2025-04-29', '2025-04-30'],
              dtype='datetime64[ns]', freq='D')

In [10]:
df = pd.DataFrame(np.random.randn(30,4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2025-04-01 -0.738534 -0.723697  1.728424 -2.108873
2025-04-02 -0.552090 -0.456210  1.296583 -0.335197
2025-04-03 -0.958737 -1.848124 -0.410648 -0.373158
2025-04-04 -0.470582 -0.671651  0.461958 -0.247030
2025-04-05  0.135923 -0.705757 -0.374821  0.786192
2025-04-06 -2.104039 -2.402322 -1.193201  0.901027
2025-04-07 -1.272441  0.564562  0.684799  0.261093
2025-04-08  0.621401  1.693100  0.191570  0.365493
2025-04-09  0.811178  0.325178 -1.526060 -0.039468
2025-04-10  0.267064  0.017312 -0.604846 -1.282471
2025-04-11  0.185312  1.624169  1.273964  0.355321
2025-04-12  1.237327 -1.223686  0.370603  1.458219
2025-04-13  2.297544 -1.409893 -1.044972 -1.368182
2025-04-14 -0.071116  0.343067  0.396499  1.700910
2025-04-15 -1.121747 -0.476481  1.203772 -1.800931
2025-04-16  0.767833 -1.542829  0.009469 -0.299606
2025-04-17 -0.808111  0.213676 -0.018175 -0.161891
2025-04-18  0.154305 -2.294987 -0.119428  0.402738
2025-04-19 -0.196692 -2.307984 -0.171345 -1.103543
2025-04-20  0.020549  0.018703 -0.534196 -0.616459
2025-04-21  0.103277  1.640509 -0.202243 -2.053419
2025-04-22 -1.042604  0.431986  1.278218  0.586779
2025-04-23 -0.868052 -1.706629  0.482448 -0.927176
2025-04-24  0.485536 -0.423840  0.995008 -0.597309
2025-04-25 -0.077711  2.406616 -1.320272  0.449279
2025-04-26  2.884393  0.824448 -0.424835  1.053650
2025-04-27  1.318201 -0.400405  1.338229 -1.447352
2025-04-28 -2.394437  0.460918  1.114512 -1.673116
2025-04-29  0.037284 -0.669689 -1.157127  0.096482
2025-04-30  0.018224 -0.805172 -0.439752  1.707119